server:
  port: 8099

spring:
  #JSON 日期格式统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 172.16.102.58
    database: 2
    port: 6379
    password: XpVdY8!58
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@172.16.64.134:1521:PROD
    username: apps
    password: qcw335657
    driver-class-name: oracle.jdbc.driver.OracleDriver

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.vivo.finance.entity
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
      # 全局逻辑删除的实体字段名(since 3.3.0)
      logic-delete-field: delFlag
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

djt-client:
  app-id: finance
  cus-id: BBK
  app-secret: rPTW0k8oTi/AcFjSVb2eMYDgswymqi2IZWiqPSAXiv4=
  sign-key: 10b26961a22c428e805929996eefa105

djt-basic:
  route-url: http://172.28.251.28/prod-api
  msg-url: http://172.28.251.28:7600/monitor/alert/sendMessage